# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ext_mcp_pb2 as ext__mcp__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ext_mcp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExtMcpStub:
    """ExtMcp is the wire protocol for an MCP-aware external policy server.
    Modeled on Envoy ext_authz, but at the MCP method layer.
    Covers both gating and mutation.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckRequest = channel.unary_unary(
                '/agentgateway.dev.ext_mcp.ExtMcp/CheckRequest',
                request_serializer=ext__mcp__pb2.McpRequest.SerializeToString,
                response_deserializer=ext__mcp__pb2.McpRequestResult.FromString,
                _registered_method=True)
        self.CheckResponse = channel.unary_unary(
                '/agentgateway.dev.ext_mcp.ExtMcp/CheckResponse',
                request_serializer=ext__mcp__pb2.McpResponse.SerializeToString,
                response_deserializer=ext__mcp__pb2.McpResponseResult.FromString,
                _registered_method=True)


class ExtMcpServicer:
    """ExtMcp is the wire protocol for an MCP-aware external policy server.
    Modeled on Envoy ext_authz, but at the MCP method layer.
    Covers both gating and mutation.
    """

    def CheckRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExtMcpServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckRequest,
                    request_deserializer=ext__mcp__pb2.McpRequest.FromString,
                    response_serializer=ext__mcp__pb2.McpRequestResult.SerializeToString,
            ),
            'CheckResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckResponse,
                    request_deserializer=ext__mcp__pb2.McpResponse.FromString,
                    response_serializer=ext__mcp__pb2.McpResponseResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentgateway.dev.ext_mcp.ExtMcp', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agentgateway.dev.ext_mcp.ExtMcp', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExtMcp:
    """ExtMcp is the wire protocol for an MCP-aware external policy server.
    Modeled on Envoy ext_authz, but at the MCP method layer.
    Covers both gating and mutation.
    """

    @staticmethod
    def CheckRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentgateway.dev.ext_mcp.ExtMcp/CheckRequest',
            ext__mcp__pb2.McpRequest.SerializeToString,
            ext__mcp__pb2.McpRequestResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentgateway.dev.ext_mcp.ExtMcp/CheckResponse',
            ext__mcp__pb2.McpResponse.SerializeToString,
            ext__mcp__pb2.McpResponseResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
